config/routes.rb
Rails.application.routes.draw do
  namespace :translation_market do
    namespace :admin do
    end
  end
  namespace :spree do
    get 'home/index'
  end

  scope module: :translation_market do
    resources :stores, except: [:index]

    namespace :admin do
      resources :language_pairs, except: [:show, :destroy]
      resources :order_categories, only: [:index, :edit, :update]
      resources :languages, only: [:index, :edit, :update]
    end
  end

  mount Spree::Core::Engine, :at => '/'

end

app/models/translation_market/language.rb
# == Schema Information
#
# Table name: spree_languages
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  position   :integer
#  active     :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module TranslationMarket
  class Language < TranslationMarket::Base
    acts_as_list

    has_many :source_language_pairs, inverse_of: :source_language, foreign_key: :source_language_id, class_name: 'TranslationMarket::LanguagePair'
    has_many :target_language_pairs, inverse_of: :target_language, foreign_key: :target_language_id, class_name: 'TranslationMarket::LanguagePair'
    has_many :target_languages, -> { uniq }, through: :source_language_pairs

    validates :code, length: { in: 1..7 }, presence: true, uniqueness: true
    validates :active, inclusion: { in: [true, false] }

    self.whitelisted_ransackable_attributes = %w[code active activated]

    scope :asc, -> { order(position: :asc) }
    scope :desc, -> { order(position: :desc) }
    scope :active, -> { unscoped.where(active: true) }
    scope :passive, -> { unscoped.where(active: false) }

    def self.source_languages
      where(id: TranslationMarket::LanguagePair.select(:source_language_id).uniq)
    end

    def self.target_languages
      where(id: TranslationMarket::LanguagePair.select(:target_language_id).uniq)
    end
  end
end

app/controllers/translation_market/admin/languages_controller.rb
module TranslationMarket
  module Admin
    class LanguagesController < TranslationMarket::Admin::ResourceController
      before_action :set_language, only: [:edit, :update]

      # GET /translation_market/admin/languages
      # GET /translation_market/admin/languages.json
      def index
        @languages_for_search = TranslationMarket::Language.all.collect { |language| [I18n.t("languages.#{language.code}"), language.id] }
        respond_with(@collection) do |format|
          format.html
        end
      end

      # GET /translation_market/admin/languages/1/edit
      def edit
      end

      # PATCH/PUT /translation_market/admin/languages/1
      # PATCH/PUT /translation_market/admin/languages/1.json
      def update
        respond_to do |format|
          if @language.update(language_params)
            flash[:success] = TranslationMarket.t(:updated_successfully)
            format.html { redirect_to main_app.admin_language_path(@language), success: TranslationMarket.t(:updated_successfully) }
          else
            format.html { render :edit }
          end
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_language
        @language = TranslationMarket::Language.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def language_params
        params.require(:language).permit(:active)
      end

      # Overrides collection method to set proper variable and data
      def collection
        return @collection if @collection.present?

        # Display all records by default.
        params[:q]             ||= {}
        params[:q][:activated] ||= '0'

        @collection = TranslationMarket::Language.all
        @collection = @collection.active if params[:q][:activated] == '1'
        @search     = @collection.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(TranslationMarket::Config[:admin_languages_per_page])
      end
    end
  end
end

app/helpers/translation_market/admin/languages_helper.rb
module TranslationMarket
  module Admin
    module LanguagesHelper
    end
  end
end

app/helpers/translation_market/language_helper.rb
module TranslationMarket
  module LanguageHelper
    def select_for_source_languages
      select_for_languages(:source_language, @source_languages, class: 'form-control')
    end

    def select_for_target_languages
      select_for_languages(:target_languages, @target_languages, class: 'form-control', multiple: true)
    end

    # Generic select tag output for languages
    def select_for_languages(name, elements, options)
      select_tag(name, options_for_select(elements.collect { |l| [l.code, l.id] }), options)
    end
  end
end

app/views/translation_market/admin/languages/_form.html.erb
<div data-hook="admin_language_pair_form_fields" class="row">
  <div class="alpha twelve columns">
    <%= f.field_container :code do %>
        <%= f.label :name, TranslationMarket.t(:name) %>
        <%= f.text_field :code, class: 'fullwidth', disabled: true, value: t("languages.#{f.object.code}") %>
        <span title="<%= TranslationMarket.t(:cannot_update_name) %>" class="fa fa-question-circle icon_link no-text with-tip"></span>
    <% end %>

    <%= f.field_container :active do %>
        <%= f.label :active do %>
            <%= f.check_box :active %> <%= TranslationMarket.t(:active) %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/translation_market/admin/languages/edit.html.erb
<%= render 'translation_market/admin/shared/title_content', key: :editing_language %>

<% content_for :page_title do %>
    <%= link_to "#{TranslationMarket.t(:editing_language)}: #{t("languages.#{@language.code}")}", edit_admin_language_path(@language) %>
<% end %>

<% content_for :page_actions do %>
    <li>
      <%= button_link_to TranslationMarket.t(:back_to_languages_list), main_app.admin_languages_path, :icon => 'arrow-left' %>
    </li>
<% end %>

<div data-hook="admin_user_new_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @language } %>
</div>

<div data-hook="admin_user_new_form">
  <%= form_for [:admin, @language], url: main_app.admin_language_path(@language), method: :put do |f| %>
      <%= render partial: 'form', locals: { f: f } %>

      <% if can?(:update, @language) %>
          <div data-hook="admin_user_edit_form_button">
            <%= render partial: 'translation_market/admin/shared/edit_resource_links', locals: { collection_url: main_app.admin_languages_path } %>
          </div>
      <% end %>
  <% end %>
</div>

app/views/translation_market/admin/languages/index.html.erb
<%= render 'translation_market/admin/shared/title_content', key: :languages %>

<% content_for :page_title do %>
    <%= TranslationMarket.t(:listing_languages) %>
<% end %>

<table class="index" id="listing_languages" data-hook>
  <colgroup>
    <col style="width: 40%">
    <col style="width: 40%">
    <col style="width: 20%">
  </colgroup>
  <thead>
  <tr data-hook="admin_languages_index_headers">
    <th><%= sort_link @search, :code, TranslationMarket.t(:name), {}, { title: 'languages_code_title' } %></th>
    <th><%= sort_link @search, :active, TranslationMarket.t(:active), {}, { title: 'languages_active_title' } %></th>
    <th data-hook="admin_languages_index_header_actions" class="actions"></th>
  </tr>
  </thead>

  <tbody>
  <% @languages.each do |language| %>
      <tr id="<%= spree_dom_id language %>" data-hook="admin_languages_index_rows" class="<%= cycle('odd', 'even') %>">
        <td class='languages_code'><%= t("languages.#{language.code}") %></td>
        <td class='language_pairs_active'><%= language.active? ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
        <td data-hook="admin_languages_index_row_actions" class="actions">
          <% if can?(:edit, language) %>
              <%= link_to_with_icon('edit', Spree.t(:edit), main_app.edit_admin_language_path(language), no_text: true) %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @languages %>

<% content_for :sidebar_title do %>
    <%= Spree.t(:search) %>
<% end %>

<% content_for :sidebar do %>
    <div class="box align-center" data-hook="admin_languages_index_search">
      <%= search_form_for [:admin, @search], url: main_app.admin_languages_path do |f| %>
          <div class="field">
            <%= f.label :id_eq, TranslationMarket.t(:name) %><br/>
            <%= f.select(:id_eq, @languages_for_search, { include_blank: Spree.t('match_choices.none') }, { class: 'select2 fullwidth' }) %>
          </div>
          <div class="field">
            <%= f.check_box :activated, { checked: params[:q][:activated] == '1' } %>
            <%= TranslationMarket.t(:active) %>
          </div>
          <div data-hook="admin_users_index_search_buttons">
            <%= button Spree.t(:search), 'search' %>
          </div>

          <br/><i class="fa fa-times"></i> <%= link_to TranslationMarket.t(:reset_search), main_app.admin_languages_path %>
      <% end %>
    </div>
<% end %>