config/routes.rb
Rails.application.routes.draw do
  namespace :translation_market do
    namespace :admin do
    end
  end
  namespace :spree do
    get 'home/index'
  end

  scope module: :translation_market do
    resources :stores, except: [:index]

    namespace :admin do
      resources :language_pairs, except: [:show, :destroy]
      resources :order_categories, only: [:index, :edit, :update]
      resources :languages, only: [:index, :edit, :update]
    end
  end

  mount Spree::Core::Engine, :at => '/'

end

app/models/translation_market/language_pair.rb
# == Schema Information
#
# Table name: spree_language_pairs
#
#  id                 :integer          not null, primary key
#  source_language_id :integer
#  target_language_id :integer
#  active             :boolean          default(FALSE)
#  word_price         :decimal(10, 2)   default(0.0)
#  translator_price   :decimal(10, 2)   default(0.0)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

module TranslationMarket
  class LanguagePair < TranslationMarket::Base
    has_one :option_value, as: :owner, dependent: :destroy, inverse_of: :owner, class_name: 'Spree::OptionValue'

    belongs_to :source_language, inverse_of: :source_language_pairs, class_name: 'TranslationMarket::Language'
    belongs_to :target_language, inverse_of: :target_language_pairs, class_name: 'TranslationMarket::Language'
    belongs_to :store, inverse_of: :language_pairs, class_name: 'Spree::Store'

    validates :source_language, presence: true
    validates :source_language_id, uniqueness: { scope: [:target_language_id, :store_id] }
    validates :target_language, presence: true
    validates :target_language_id, uniqueness: { scope: [:source_language_id, :store_id] }
    validates :active, inclusion: { in: [true, false] }
    validates :store, presence: true
    validate :cant_pair_with_self

    after_create :create_option_values

    alias_attribute :multiply_by, :word_price

    self.whitelisted_ransackable_attributes = %w[source_language_id target_language_id word_price translator_price active activated]
    self.whitelisted_ransackable_associations = %w[source_language target_language]

    scope :active, -> { unscoped.where(active: true) }
    scope :passive, -> { unscoped.where(active: false) }

    def reverse_language_pair
      TranslationMarket::LanguagePair.find_by(source_language_id: target_language_id, target_language_id: source_language_id)
    end
    alias :reverse :reverse_language_pair

    private
    def cant_pair_with_self
      if source_language_id == target_language_id && source_language_id.present?
        errors.add(:target_language_id, "can't be the same as source language")
      end
    end

    # Creates option values when admin creates a language pair
    def create_option_values
      ::Spree::OptionType.find_or_create_for_language_pair.option_values.create(name: "#{source_language.code}-#{target_language.code}", presentation: "#{source_language.code} -> #{target_language.code}", owner: self)
    end
  end
end

app/controllers/translation_market/admin/language_pairs_controller.rb
module TranslationMarket
  module Admin
    class LanguagePairsController < TranslationMarket::Admin::ResourceController
      before_action :set_language_pair, only: [:edit, :update, :destroy]
      before_action :set_languages

      # GET /translation_market/admin/language_pairs
      # GET /translation_market/admin/language_pairs.json
      def index
        respond_with(@collection) do |format|
          format.html
        end
      end

      # GET /translation_market/admin/language_pairs/new
      def new
        @language_pair = TranslationMarket::LanguagePair.new
      end

      # GET /translation_market/admin/language_pairs/1/edit
      def edit
      end

      # POST /translation_market/admin/language_pairs
      # POST /translation_market/admin/language_pairs.json
      def create
        @language_pair = TranslationMarket::LanguagePair.new(language_pair_params)

        respond_to do |format|
          if @language_pair.save

            flash[:success] = TranslationMarket.t(:created_successfully)
            format.html { redirect_to main_app.admin_language_pairs_path, success: TranslationMarket.t(:created_successfully) }
          else
            format.html { render :new }
          end
        end
      end

      # PATCH/PUT /translation_market/admin/language_pairs/1
      # PATCH/PUT /translation_market/admin/language_pairs/1.json
      def update
        respond_to do |format|
          if @language_pair.update(language_pair_params)

            flash[:success] = TranslationMarket.t(:updated_successfully)
            format.html { redirect_to main_app.admin_language_pairs_path, success: TranslationMarket.t(:updated_successfully) }
          else
            format.html { render :edit }
          end
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_language_pair
        @language_pair = TranslationMarket::LanguagePair.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def language_pair_params
        params.require(:translation_market_language_pair).permit(:source_language_id, :target_language_id, :active, :word_price, :translator_price)
      end

      # Overrides collection method to set proper variable and data
      def collection
        return @collection if @collection.present?

        # Display all records by default.
        params[:q]             ||= {}
        params[:q][:activated] ||= '0'

        @collection = TranslationMarket::LanguagePair.includes(:source_language, :target_language)
        @collection = @collection.active if params[:q][:activated] == '1'
        @search     = @collection.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(TranslationMarket::Config[:admin_language_pairs_per_page])
      end

      # Sets active languages as @languages for language pair create action.
      def set_languages
        @languages = TranslationMarket::Language.active.asc.collect { |language| [I18n.t("languages.#{language.code}"), language.id] }
      end
    end
  end
end

app/helpers/translation_market/admin/language_pairs_helper.rb
module TranslationMarket
  module Admin
    module LanguagePairsHelper
      # Outputs language pair as string
      # with localization
      # examle: 'Turkish > English'
      def language_pair_as_string(language_pair)
        "#{I18n.t("languages.#{language_pair.source_language.code}")} > #{I18n.t("languages.#{language_pair.target_language.code}")}"
      end
    end
  end
end

app/views/translation_market/admin/language_pairs/_form.html.erb
<div data-hook="admin_language_pair_form_fields" class="row">
  <div class="alpha six columns">
    <%= f.field_container :source_language_id do %>
        <%= f.label :source_language_id, TranslationMarket.t(:source_language) %>
        <% if @language_pair.new_record? %>
            <%= f.select(:source_language_id, @languages, { include_blank: Spree.t('match_choices.none') }, { class: 'select2 fullwidth' }) %>
            <%= error_message_on :language_pair, :source_language %>
            <%= error_message_on :language_pair, :source_language_id %>
        <% else %>
            <%= f.select(:source_language_id, @languages, { include_blank: Spree.t('match_choices.none') }, { class: 'select2 fullwidth', disabled: true }) %>
            <span title="<%= TranslationMarket.t(:cannot_update_source_language) %>" class="fa fa-question-circle icon_link no-text with-tip"></span>
        <% end %>
    <% end %>

    <%= f.field_container :target_language_id do %>
        <%= f.label :target_language_id, TranslationMarket.t(:target_language) %>
        <% if @language_pair.new_record? %>
            <%= f.select(:target_language_id, @languages, { include_blank: Spree.t('match_choices.none') }, { class: 'select2 fullwidth' }) %>
            <%= error_message_on :language_pair, :target_language %>
            <%= error_message_on :language_pair, :target_language_id %>
        <% else %>
            <%= f.select(:target_language_id, @languages, { include_blank: Spree.t('match_choices.none') }, { class: 'select2 fullwidth', disabled: true }) %>
            <span title="<%= TranslationMarket.t(:cannot_update_target_language) %>" class="fa fa-question-circle icon_link no-text with-tip"></span>
        <% end %>
    <% end %>
  </div>

  <div data-hook="admin_language_pair_form_price_fields" class="omega six columns">
    <%= f.field_container :word_price do %>
        <%= f.label :word_price, TranslationMarket.t(:word_price) %>
        <%= f.number_field :word_price, class: 'fullwidth' %>
        <%= error_message_on :language_pair, :word_price %>
    <% end %>

    <%= f.field_container :translator_price do %>
        <%= f.label :translator_price, TranslationMarket.t(:translator_price) %>
        <%= f.number_field :translator_price, class: 'fullwidth' %>
        <%= error_message_on :language_pair, :translator_price %>
    <% end %>

    <%= f.field_container :active do %>
        <%= f.label :active do %>
            <%= f.check_box :active %> <%= TranslationMarket.t(:active) %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/translation_market/admin/language_pairs/edit.html.erb
<%= render 'translation_market/admin/shared/title_content', key: :editing_language_pair %>

<% content_for :page_title do %>
    <%= link_to "#{TranslationMarket.t(:editing_language_pair)}: #{language_pair_as_string(@language_pair)}", edit_admin_language_pair_path(@language_pair) %>
<% end %>

<% content_for :page_actions do %>
    <li>
      <%= button_link_to TranslationMarket.t(:back_to_language_pairs_list), main_app.admin_language_pairs_path, :icon => 'arrow-left' %>
    </li>
<% end %>

<div data-hook="admin_user_new_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @language_pair } %>
</div>

<div data-hook="admin_user_new_form">
  <%= form_for [:admin, @language_pair], url: main_app.admin_language_pair_path(@language_pair), method: :put do |f| %>
      <%= render partial: 'form', locals: { f: f } %>

      <% if can?(:update, @language_pair) %>
          <div data-hook="admin_user_edit_form_button">
            <%= render partial: 'translation_market/admin/shared/edit_resource_links', locals: { collection_url: main_app.admin_language_pairs_path } %>
          </div>
      <% end %>
  <% end %>
</div>

app/views/translation_market/admin/language_pairs/index.html.erb
<%= render 'translation_market/admin/shared/title_content', key: :language_pairs %>

<% content_for :page_title do %>
    <%= TranslationMarket.t(:listing_language_pairs) %>
<% end %>

<% content_for :page_actions do %>
    <% if can?(:admin, TranslationMarket::LanguagePair) && can?(:create, TranslationMarket::LanguagePair) %>
        <li>
          <%= button_link_to TranslationMarket.t(:new_language_pair), main_app.new_admin_language_pair_path, :icon => 'plus', :id => 'admin_new_language_pair_link' %>
        </li>
    <% end %>
<% end %>

<table class="index" id="listing_language_pairs" data-hook>
  <colgroup>
    <col style="width: 25%">
    <col style="width: 25%">
    <col style="width: 10%">
    <col style="width: 10%">
    <col style="width: 5%">
    <col style="width: 15%">
  </colgroup>
  <thead>
  <tr data-hook="admin_language_pairs_index_headers">
    <th><%= sort_link @search, :source_language_code, TranslationMarket.t(:source_language), {}, { title: 'language_pairs_source_language_title' } %></th>
    <th><%= sort_link @search, :target_language_code, TranslationMarket.t(:target_language), {}, { title: 'language_pairs_target_language_title' } %></th>
    <th><%= sort_link @search, :word_price, TranslationMarket.t(:word_price), {}, { title: 'language_pairs_word_price_title' } %></th>
    <th><%= sort_link @search, :translator_price, TranslationMarket.t(:translator_price), {}, { title: 'language_pairs_translator_price_title' } %></th>
    <th><%= sort_link @search, :active, TranslationMarket.t(:active), {}, { title: 'language_pairs_active_title' } %></th>
    <th data-hook="admin_language_pairs_index_header_actions" class="actions"></th>
  </tr>
  </thead>

  <tbody>
  <% @language_pairs.each do |language_pair| %>
      <tr id="<%= spree_dom_id language_pair %>" data-hook="admin_language_pairs_index_rows" class="<%= cycle('odd', 'even') %>">
        <td class='language_pairs_source_language'><%= t("languages.#{language_pair.source_language.code}") %></td>
        <td class='language_pairs_target_language'><%= t("languages.#{language_pair.target_language.code}") %></td>
        <td class='language_pairs_word_price'><%= number_to_currency language_pair.word_price %></td>
        <td class='language_pairs_translator_price'><%= number_to_currency language_pair.translator_price %></td>
        <td class='language_pairs_active'><%= language_pair.active? ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
        <td data-hook="admin_language_pairs_index_row_actions" class="actions">
          <% if can?(:edit, language_pair) %>
              <%= link_to_with_icon('edit', Spree.t(:edit), main_app.edit_admin_language_pair_path(language_pair), no_text: true) %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @language_pairs %>

<% content_for :sidebar_title do %>
    <%= Spree.t(:search) %>
<% end %>

<% content_for :sidebar do %>
    <div class="box align-center" data-hook="admin_language_pairs_index_search">
      <%= search_form_for [:admin, @search], url: main_app.admin_language_pairs_path do |f| %>
          <div class="field">
            <%= f.label :source_language_id_eq, TranslationMarket.t(:source_language) %><br/>
            <%= f.select(:source_language_id_eq, @languages, { include_blank: Spree.t('match_choices.none') }, { class: 'select2 fullwidth' }) %>
          </div>
          <div class="field">
            <%= f.label :target_language_id_eq, TranslationMarket.t(:target_language) %><br/>
            <%= f.select(:target_language_id_eq, @languages, { include_blank: Spree.t('match_choices.none') }, { class: 'select2 fullwidth' }) %>
          </div>
          <div class="number-range-filter field">
            <%= f.label :word_price_gteq, TranslationMarket.t(:word_price) %><br/>
            <%= f.text_field :word_price_gteq, class: 'pricepicker' %>
            <span class="range-divider">
                <i class="fa fa-arrow-right"></i>
            </span>
            <%= f.text_field :word_price_lteq, class: 'pricepicker' %>
          </div>
          <div class="number-range-filter field">
            <%= f.label :translator_price_gteq, TranslationMarket.t(:translator_price) %><br/>
            <%= f.text_field :translator_price_gteq, class: 'pricepicker' %>
            <span class="range-divider">
                <i class="fa fa-arrow-right"></i>
            </span>
            <%= f.text_field :translator_price_lteq, class: 'pricepicker' %>
          </div>
          <div class="field">
            <%= f.check_box :activated, { checked: params[:q][:activated] == '1' } %>
            <%= TranslationMarket.t(:active) %>
          </div>
          <div data-hook="admin_users_index_search_buttons">
            <%= button Spree.t(:search), 'search' %>
          </div>
          
          <br/><i class="fa fa-times"></i> <%= link_to TranslationMarket.t(:reset_search), main_app.admin_language_pairs_path %>
      <% end %>
    </div>
<% end %>

app/views/translation_market/admin/language_pairs/new.html.erb
<%= render 'translation_market/admin/shared/title_content', key: :new_language_pair %>

<% content_for :page_title do %>
    <%= TranslationMarket.t(:new_language_pair) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to TranslationMarket.t(:back_to_language_pairs_list), main_app.admin_language_pairs_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<div data-hook="admin_user_new_form_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @language_pair } %>
</div>

<div data-hook="admin_user_new_form">
  <%= form_for [:admin, @language_pair], url: main_app.admin_language_pairs_path, method: :post do |f| %>
      <%= render partial: 'form', locals: { f: f } %>

      <div data-hook="admin_user_new_form_buttons">
        <%= render 'translation_market/admin/shared/new_resource_links', url: main_app.admin_language_pairs_path %>
      </div>
  <% end %>
</div>